version: build{build}
image: Visual Studio 2017
branches:
  except:
    - project/travis

platform: 
  - x64
install:
  - vcpkg install directxtk:x64-windows directxtex:x64-windows
build:
  verbosity: normal
  project: HelloDirectX.sln

test: off