version: build{build}
image: Visual Studio 2017
branches:
  except:
    - project/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
install:
  - vcpkg install directxtk:x64-windows
build:
  verbosity: normal
  project: HelloDirectX.sln

test: off